---
fixtures:
  forge_modules:
    rpmkey:
      repo: 'stschulte/rpmkey'
      ref: '1.0.3'
    xinetd:
      repo: 'puppetlabs/xinetd'
      ref: '3.2.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '6.0.0'
      # flags: "--module_repository https://my_repo.com"
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '8.1.0'
    firewall:
      repo: 'puppetlabs/firewall'
      ref: '2.0.0'
    yumrepo_core:
      repo: 'puppetlabs/yumrepo_core'
      ref: '1.0.3'

