spec/spec_helper.rb:
  spec_overrides: |-
    RSpec.configure do |c|
      c.default_facts = default_facts
      c.hiera_config = 'spec/hiera.yaml'
      c.before :each do
        Puppet.settings[:strict] = :warning
      end
    end
